#!/usr/bin/perl -w

# Copyright (C) 2016 Stefano Zacchiroli <zack@upsilon.cc>
# License: GNU General Public License (GPL), version 3 or above

# convert a ledger-cli commodities file to beancount format

# TODO

use strict;
use warnings;

my $commodities_date = "1970-01-01";  # unix epoch, just because
my $indent = "  ";

sub print_metadata($$) {
    my ($key, $value) = @_;
    print "$indent", lc($key), ": \"$value\"\n";
}

while (my $l = <>) {
    chomp $l;

    if ($l =~ /^commodity\s+(.*)/) {  # account declaration
	print "$commodities_date commodity $1\n";
    } elsif ($l =~ /^\s+note\s+(.*)/) {  # note
	print_metadata("name", $1);
    } elsif ($l =~ /^\s+format\s+(.*)/) {  # format
	next;  # skip directive, not needed in beancount
    } else {
	print "$l\n";
    }
}
