#!/bin/sh

status=0

test_conversion () {
	file=$1
	test=$(basename "$file")
	expected=$(echo $file | sed -e 's/.ledger$/.beancount/')

	actual=$(tempfile)

	printf "Converting $test... "

	config=ledger2beancount.yml
	test=$(echo $test | sed 's/.ledger$//')
	if [ -e $test.yml ]; then
		config=$test.yml
	fi

	cat $file | ../bin/ledger2beancount --config $config > $actual

	if $(cmp -s $expected $actual); then
		echo "ok"
	else
		status=1
		echo "FAIL"
		diff -urN $expected $actual | tail -n +3
	fi

	rm -f $actual
}

test_validity () {
	file=$1
	test=$(basename "$file")
	printf "Validating $test... "
	if bean-check $test; then
		echo "ok"
	else
		echo "FAIL"
		status=1
	fi
}

export LC_ALL=C.UTF-8

for test in `find . -name "*.ledger" | sort`; do
	test_conversion "$test"
done

for test in `find . -name "*.beancount" | sort`; do
	test_validity "$test"
done

exit $status

