#!/bin/sh

status=0

test_conversion () {
	file=$1
	test=$(basename "$file")
	expected=$(echo $file | sed -e 's/.ledger$/.beancount/')

	actual=$(tempfile)

	printf "Converting $test... "

	config=ledger2beancount.yml
	test=$(echo $test | sed 's/.ledger$//')
	if [ -e $test.yml ]; then
		config=$test.yml
	fi

	cat $file | ../bin/ledger2beancount --config $config > $actual

	if $(cmp -s $expected $actual); then
		echo "ok"
	else
		status=1
		echo "FAIL"
		diff -urN $expected $actual | tail -n +3
	fi

	rm -f $actual
}

test_validity_ledger () {
	file=$1
	test=$(basename "$file")
	printf "Validating $test... "
	if ledger --init-file /dev/null -f $test bal > /dev/null; then
		echo "ok"
	else
		echo "FAIL"
		status=1
	fi
}

test_validity_beancount () {
	file=$1
	test=$(basename "$file")
	printf "Validating $test... "
	if bean-check $test; then
		echo "ok"
	else
		echo "FAIL"
		status=1
	fi
}

export LC_ALL=C.UTF-8

version=$(ledger --version | grep "^Ledger [0-9]" | cut -d " " -f 2 | cut -d . -f 1)
if [ $version -eq 2 ]; then
	echo "Skipping ledger validation checks since version ledger 2 is too old"
else
	for test in `find . -name "*.ledger" | sort`; do
		test_validity_ledger "$test"
	done
fi

for test in `find . -name "*.ledger" | sort`; do
	test_conversion "$test"
done

for test in `find . -name "*.beancount" | sort`; do
	test_validity_beancount "$test"
done

exit $status

